---
title: My First Page
date: 2020-07-02
---
author: Selena Richards
email: selena.radaza
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I have no idea what I'm doing.

# social links
twitter_username: icyangels452 # DO NOT include the @ character, or else the build will fail!
github_username:  selena-radaza # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
